#全局最短路径规划算法配置文件
#2022-05-13

# 数据库设置
mysql:
    host: "10.173.27.120"
    database: "v5.3_robot"
    user: "root"
    password: "mengpa@.."
    port: 3306
    charset: "utf8"

# 数据库表设置-构建路由表所需
table:
    position_table: "test_robot_position"        # 机器人位置表名称
    begin_id: "position_num"   # 巡检点编号
    position: "position"       # 巡检点位置
    stop_id: "stop_id"         # 巡检点的连通关系(可到达点)

    route_table: "robot_position_route"   # 新建的路由表名称
    BeginId: "begin_id"        # 起点
    StopId: "stop_id"          # 终点
    Distance: "distance"      # 距离
